# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shared_contracts/protos/image_encoding_service/image_encoding_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shared_contracts/protos/image_encoding_service/image_encoding_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKshared_contracts/protos/image_encoding_service/image_encoding_service.proto\"3\n\x0cImageRequest\x12\x13\n\x0bquery_image\x18\x01 \x01(\x0c\x12\x0e\n\x06job_id\x18\x02 \x01(\t\"6\n\rImageResponse\x12\x15\n\rencoded_image\x18\x01 \x03(\x02\x12\x0e\n\x06job_id\x18\x02 \x01(\t2E\n\x14ImageEncodingService\x12-\n\x0c\x65ncode_image\x12\r.ImageRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shared_contracts.protos.image_encoding_service.image_encoding_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=79
  _globals['_IMAGEREQUEST']._serialized_end=130
  _globals['_IMAGERESPONSE']._serialized_start=132
  _globals['_IMAGERESPONSE']._serialized_end=186
  _globals['_IMAGEENCODINGSERVICE']._serialized_start=188
  _globals['_IMAGEENCODINGSERVICE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
