# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared_contracts.protos.image_encoding_service import image_encoding_service_pb2 as shared__contracts_dot_protos_dot_image__encoding__service_dot_image__encoding__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shared_contracts/protos/image_encoding_service/image_encoding_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageEncodingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.encode_image = channel.unary_unary(
                '/ImageEncodingService/encode_image',
                request_serializer=shared__contracts_dot_protos_dot_image__encoding__service_dot_image__encoding__service__pb2.ImageRequest.SerializeToString,
                response_deserializer=shared__contracts_dot_protos_dot_image__encoding__service_dot_image__encoding__service__pb2.ImageResponse.FromString,
                _registered_method=True)


class ImageEncodingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def encode_image(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageEncodingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'encode_image': grpc.unary_unary_rpc_method_handler(
                    servicer.encode_image,
                    request_deserializer=shared__contracts_dot_protos_dot_image__encoding__service_dot_image__encoding__service__pb2.ImageRequest.FromString,
                    response_serializer=shared__contracts_dot_protos_dot_image__encoding__service_dot_image__encoding__service__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageEncodingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ImageEncodingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageEncodingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def encode_image(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ImageEncodingService/encode_image',
            shared__contracts_dot_protos_dot_image__encoding__service_dot_image__encoding__service__pb2.ImageRequest.SerializeToString,
            shared__contracts_dot_protos_dot_image__encoding__service_dot_image__encoding__service__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
