# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared_contracts.protos.indexing_service import indexing_service_pb2 as shared__contracts_dot_protos_dot_indexing__service_dot_indexing__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shared_contracts/protos/indexing_service/indexing_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IndexingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.index_images = channel.unary_unary(
                '/IndexingService/index_images',
                request_serializer=shared__contracts_dot_protos_dot_indexing__service_dot_indexing__service__pb2.IndexImagesRequest.SerializeToString,
                response_deserializer=shared__contracts_dot_protos_dot_indexing__service_dot_indexing__service__pb2.IndexImagesResponse.FromString,
                _registered_method=True)


class IndexingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def index_images(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'index_images': grpc.unary_unary_rpc_method_handler(
                    servicer.index_images,
                    request_deserializer=shared__contracts_dot_protos_dot_indexing__service_dot_indexing__service__pb2.IndexImagesRequest.FromString,
                    response_serializer=shared__contracts_dot_protos_dot_indexing__service_dot_indexing__service__pb2.IndexImagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IndexingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('IndexingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IndexingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def index_images(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/IndexingService/index_images',
            shared__contracts_dot_protos_dot_indexing__service_dot_indexing__service__pb2.IndexImagesRequest.SerializeToString,
            shared__contracts_dot_protos_dot_indexing__service_dot_indexing__service__pb2.IndexImagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
