from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetHealth500Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error_message=None):  # noqa: E501
        """GetHealth500Response - a model defined in OpenAPI

        :param error_message: The error_message of this GetHealth500Response.  # noqa: E501
        :type error_message: str
        """
        self.openapi_types = {
            'error_message': str
        }

        self.attribute_map = {
            'error_message': 'error_message'
        }

        self._error_message = error_message

    @classmethod
    def from_dict(cls, dikt) -> 'GetHealth500Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getHealth_500_response of this GetHealth500Response.  # noqa: E501
        :rtype: GetHealth500Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_message(self) -> str:
        """Gets the error_message of this GetHealth500Response.


        :return: The error_message of this GetHealth500Response.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this GetHealth500Response.


        :param error_message: The error_message of this GetHealth500Response.
        :type error_message: str
        """

        self._error_message = error_message
