from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class IndexImages200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, job_id=None, message=None):  # noqa: E501
        """IndexImages200Response - a model defined in OpenAPI

        :param job_id: The job_id of this IndexImages200Response.  # noqa: E501
        :type job_id: str
        :param message: The message of this IndexImages200Response.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'job_id': str,
            'message': str
        }

        self.attribute_map = {
            'job_id': 'job_id',
            'message': 'message'
        }

        self._job_id = job_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'IndexImages200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The indexImages_200_response of this IndexImages200Response.  # noqa: E501
        :rtype: IndexImages200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def job_id(self) -> str:
        """Gets the job_id of this IndexImages200Response.


        :return: The job_id of this IndexImages200Response.
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id: str):
        """Sets the job_id of this IndexImages200Response.


        :param job_id: The job_id of this IndexImages200Response.
        :type job_id: str
        """
        if job_id is None:
            raise ValueError("Invalid value for `job_id`, must not be `None`")  # noqa: E501

        self._job_id = job_id

    @property
    def message(self) -> str:
        """Gets the message of this IndexImages200Response.


        :return: The message of this IndexImages200Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this IndexImages200Response.


        :param message: The message of this IndexImages200Response.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
