from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class IndexImagesRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, image_storage_bucket=None, metadata_storage_bucket=None):  # noqa: E501
        """IndexImagesRequest - a model defined in OpenAPI

        :param image_storage_bucket: The image_storage_bucket of this IndexImagesRequest.  # noqa: E501
        :type image_storage_bucket: str
        :param metadata_storage_bucket: The metadata_storage_bucket of this IndexImagesRequest.  # noqa: E501
        :type metadata_storage_bucket: str
        """
        self.openapi_types = {
            'image_storage_bucket': str,
            'metadata_storage_bucket': str
        }

        self.attribute_map = {
            'image_storage_bucket': 'image_storage_bucket',
            'metadata_storage_bucket': 'metadata_storage_bucket'
        }

        self._image_storage_bucket = image_storage_bucket
        self._metadata_storage_bucket = metadata_storage_bucket

    @classmethod
    def from_dict(cls, dikt) -> 'IndexImagesRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The indexImages_request of this IndexImagesRequest.  # noqa: E501
        :rtype: IndexImagesRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_storage_bucket(self) -> str:
        """Gets the image_storage_bucket of this IndexImagesRequest.


        :return: The image_storage_bucket of this IndexImagesRequest.
        :rtype: str
        """
        return self._image_storage_bucket

    @image_storage_bucket.setter
    def image_storage_bucket(self, image_storage_bucket: str):
        """Sets the image_storage_bucket of this IndexImagesRequest.


        :param image_storage_bucket: The image_storage_bucket of this IndexImagesRequest.
        :type image_storage_bucket: str
        """
        if image_storage_bucket is None:
            raise ValueError("Invalid value for `image_storage_bucket`, must not be `None`")  # noqa: E501

        self._image_storage_bucket = image_storage_bucket

    @property
    def metadata_storage_bucket(self) -> str:
        """Gets the metadata_storage_bucket of this IndexImagesRequest.


        :return: The metadata_storage_bucket of this IndexImagesRequest.
        :rtype: str
        """
        return self._metadata_storage_bucket

    @metadata_storage_bucket.setter
    def metadata_storage_bucket(self, metadata_storage_bucket: str):
        """Sets the metadata_storage_bucket of this IndexImagesRequest.


        :param metadata_storage_bucket: The metadata_storage_bucket of this IndexImagesRequest.
        :type metadata_storage_bucket: str
        """
        if metadata_storage_bucket is None:
            raise ValueError("Invalid value for `metadata_storage_bucket`, must not be `None`")  # noqa: E501

        self._metadata_storage_bucket = metadata_storage_bucket
