from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class InlineObject1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error_message=None):  # noqa: E501
        """InlineObject1 - a model defined in OpenAPI

        :param error_message: The error_message of this InlineObject1.  # noqa: E501
        :type error_message: str
        """
        self.openapi_types = {
            'error_message': str
        }

        self.attribute_map = {
            'error_message': 'error_message'
        }

        self._error_message = error_message

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_1 of this InlineObject1.  # noqa: E501
        :rtype: InlineObject1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_message(self) -> str:
        """Gets the error_message of this InlineObject1.


        :return: The error_message of this InlineObject1.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this InlineObject1.


        :param error_message: The error_message of this InlineObject1.
        :type error_message: str
        """

        self._error_message = error_message
