from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class RetrievedImage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, image_url=None, similarity_score=None):  # noqa: E501
        """RetrievedImage - a model defined in OpenAPI

        :param image_url: The image_url of this RetrievedImage.  # noqa: E501
        :type image_url: str
        :param similarity_score: The similarity_score of this RetrievedImage.  # noqa: E501
        :type similarity_score: float
        """
        self.openapi_types = {
            'image_url': str,
            'similarity_score': float
        }

        self.attribute_map = {
            'image_url': 'image_url',
            'similarity_score': 'similarity_score'
        }

        self._image_url = image_url
        self._similarity_score = similarity_score

    @classmethod
    def from_dict(cls, dikt) -> 'RetrievedImage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RetrievedImage of this RetrievedImage.  # noqa: E501
        :rtype: RetrievedImage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_url(self) -> str:
        """Gets the image_url of this RetrievedImage.


        :return: The image_url of this RetrievedImage.
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url: str):
        """Sets the image_url of this RetrievedImage.


        :param image_url: The image_url of this RetrievedImage.
        :type image_url: str
        """
        if image_url is None:
            raise ValueError("Invalid value for `image_url`, must not be `None`")  # noqa: E501

        self._image_url = image_url

    @property
    def similarity_score(self) -> float:
        """Gets the similarity_score of this RetrievedImage.


        :return: The similarity_score of this RetrievedImage.
        :rtype: float
        """
        return self._similarity_score

    @similarity_score.setter
    def similarity_score(self, similarity_score: float):
        """Sets the similarity_score of this RetrievedImage.


        :param similarity_score: The similarity_score of this RetrievedImage.
        :type similarity_score: float
        """
        if similarity_score is None:
            raise ValueError("Invalid value for `similarity_score`, must not be `None`")  # noqa: E501

        self._similarity_score = similarity_score
