from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.retrieved_image import RetrievedImage
from openapi_server import util

from openapi_server.models.retrieved_image import RetrievedImage  # noqa: E501

class SearchImages200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, similar_images=None, processing_ms=None, search_id=None):  # noqa: E501
        """SearchImages200Response - a model defined in OpenAPI

        :param similar_images: The similar_images of this SearchImages200Response.  # noqa: E501
        :type similar_images: List[RetrievedImage]
        :param processing_ms: The processing_ms of this SearchImages200Response.  # noqa: E501
        :type processing_ms: float
        :param search_id: The search_id of this SearchImages200Response.  # noqa: E501
        :type search_id: str
        """
        self.openapi_types = {
            'similar_images': List[RetrievedImage],
            'processing_ms': float,
            'search_id': str
        }

        self.attribute_map = {
            'similar_images': 'similar_images',
            'processing_ms': 'processing_ms',
            'search_id': 'search_id'
        }

        self._similar_images = similar_images
        self._processing_ms = processing_ms
        self._search_id = search_id

    @classmethod
    def from_dict(cls, dikt) -> 'SearchImages200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The searchImages_200_response of this SearchImages200Response.  # noqa: E501
        :rtype: SearchImages200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def similar_images(self) -> List[RetrievedImage]:
        """Gets the similar_images of this SearchImages200Response.


        :return: The similar_images of this SearchImages200Response.
        :rtype: List[RetrievedImage]
        """
        return self._similar_images

    @similar_images.setter
    def similar_images(self, similar_images: List[RetrievedImage]):
        """Sets the similar_images of this SearchImages200Response.


        :param similar_images: The similar_images of this SearchImages200Response.
        :type similar_images: List[RetrievedImage]
        """
        if similar_images is None:
            raise ValueError("Invalid value for `similar_images`, must not be `None`")  # noqa: E501

        self._similar_images = similar_images

    @property
    def processing_ms(self) -> float:
        """Gets the processing_ms of this SearchImages200Response.


        :return: The processing_ms of this SearchImages200Response.
        :rtype: float
        """
        return self._processing_ms

    @processing_ms.setter
    def processing_ms(self, processing_ms: float):
        """Sets the processing_ms of this SearchImages200Response.


        :param processing_ms: The processing_ms of this SearchImages200Response.
        :type processing_ms: float
        """
        if processing_ms is None:
            raise ValueError("Invalid value for `processing_ms`, must not be `None`")  # noqa: E501

        self._processing_ms = processing_ms

    @property
    def search_id(self) -> str:
        """Gets the search_id of this SearchImages200Response.


        :return: The search_id of this SearchImages200Response.
        :rtype: str
        """
        return self._search_id

    @search_id.setter
    def search_id(self, search_id: str):
        """Sets the search_id of this SearchImages200Response.


        :param search_id: The search_id of this SearchImages200Response.
        :type search_id: str
        """
        if search_id is None:
            raise ValueError("Invalid value for `search_id`, must not be `None`")  # noqa: E501

        self._search_id = search_id
