# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/search_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/search_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/search_service.proto\"7\n\rSearchRequest\x12\x11\n\tjpg_image\x18\x01 \x01(\x0c\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\"/\n\x0eSearchResponse\x12\x1d\n\x07results\x18\x01 \x03(\x0b\x32\x0c.ImageResult\"Y\n\x0bImageResult\x12\x11\n\timage_url\x18\x01 \x01(\t\x12\x18\n\x10similarity_score\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x32:\n\rSearchService\x12)\n\x06search\x12\x0e.SearchRequest\x1a\x0f.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.search_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=30
  _globals['_SEARCHREQUEST']._serialized_end=85
  _globals['_SEARCHRESPONSE']._serialized_start=87
  _globals['_SEARCHRESPONSE']._serialized_end=134
  _globals['_IMAGERESULT']._serialized_start=136
  _globals['_IMAGERESULT']._serialized_end=225
  _globals['_SEARCHSERVICE']._serialized_start=227
  _globals['_SEARCHSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
